### ISSUE TITLE
Error in other Files

### ISSUE THREAD

**Issue by wodka** [wodka/phpspec-idea#3]
12:05:56 PM NullPointerException: null
12:05:58 PM NullPointerException: null
12:05:59 PM NullPointerException: null
12:06:02 PM NullPointerException: null
12:06:04 PM NullPointerException: null
12:07:27 PM NullPointerException: null
12:07:37 PM NullPointerException: null
12:08:04 PM NullPointerException: null

```
null
java.lang.NullPointerException
    at pl.projectspace.idea.plugins.php.phpspec.code.type.provider.WrappedObjectTypeProvider.getTypeFor(WrappedObjectTypeProvider.java:45)
    at pl.projectspace.idea.plugins.commons.php.code.type.GenericTypeProvider.getType(GenericTypeProvider.java:58)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:42)
    at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:37)
```

**Comment by wodka** [comment]
I think this is more than just checking where in the file we are...

https://github.com/wodka/phpstorm-phpspec/blob/master/src/pl/projectspace/idea/plugins/php/phpspec/code/SpecCompletionProvider.java#L31

**Comment by wodka** [comment]
original is resolved...

now this is new: 
1:09:45 PM Throwable: Icon cannot be found in '/at/ms07/phpspec/idea/plugins/icons/phpspec_16_16.png', aClass='class at.ms07.phpspec.idea.plugin.core.PhpSpecIcons'

**Comment by wodka** [comment]
fixed
